# Cloudflare Pages Configuration

# Build command
[build]
  command = "npm run build"
  publish = "dist"

# Build environment variables
[build.environment]
  NODE_VERSION = "18"

# Headers for camera permissions and security
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "camera=*, accelerometer=*, gyroscope=*, magnetometer=*"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
